source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'DTTableViewManager.xcodeproj'
platform :ios, 7.0

use_frameworks!

target :Example do
	pod 'DTModelStorage', '1.1.1'
end

target :Tests do
	pod 'DTModelStorage', '1.1.1'
	pod 'Cedar', '0.9.8'
    pod 'OCMock', '~> 2.2'
end
