source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'DTTableViewManager.xcodeproj'
platform :ios, 7.0

target :Example do
	pod 'DTModelStorage', :head
end

target :XCTests do
	pod 'DTModelStorage', :head
	pod 'Cedar'
    pod 'OCMock', '~> 2.2'
end
