author: Denys Telezhkin
author_url: https://github.com/DenTelezhkin
github_url: https://github.com/DenTelezhkin/DTTableViewManager
root_url: https://dentelezhkin.github.io/DTTableViewManager/
module: DTTableViewManager
xcodebuild_arguments: [-scheme, DTTableViewManager, -sdk, iphonesimulator]
output: docs
theme: fullwidth
